public enum Tag {
  public enum A {}
  public enum Abbr {}
  public enum Address {}
  public enum Area {}
  public enum Article {}
  public enum Aside {}
  public enum Audio {}
  public enum B {}
  public enum Base {}
  public enum Bdi {}
  public enum Bdo {}
  public enum Blockquote {}
  public enum Body {}
  public enum Button {}
  public enum Canvas {}
  public enum Caption {}
  public enum Cite {}
  public enum Code {}
  public enum Col {}
  public enum Colgroup {}
  public enum Dd {}
  public enum Del {}
  public enum Details {}
  public enum Dfn {}
  public enum Div {}
  public enum Dl {}
  public enum Dt {}
  public enum Em {}
  public enum Embed {}
  public enum Fieldset {}
  public enum Figcaption {}
  public enum Figure {}
  public enum Footer {}
  public enum Form {}
  public enum H1 {}
  public enum H2 {}
  public enum H3 {}
  public enum H4 {}
  public enum H5 {}
  public enum H6 {}
  public enum Head {}
  public enum Header {}
  public enum Hr {}
  public enum Html {}
  public enum I {}
  public enum Iframe {}
  public enum Img {}
  public enum Input {}
  public enum Ins {}
  public enum Kbd {}
  public enum Label {}
  public enum Legend {}
  public enum Li {}
  public enum Link {}
  public enum Main {}
  public enum Mark {}
  public enum Map {}
  public enum Meta {}
  public enum Meter {}
  public enum Nav {}
  public enum Object {}
  public enum Ol {}
  public enum Optgroup {}
  public enum Option {}
  public enum Output {}
  public enum P {}
  public enum Param {}
  public enum Picture {}
  public enum Pre {}
  public enum Progress {}
  public enum Q {}
  public enum Rp {}
  public enum Rt {}
  public enum Ruby {}
  public enum S {}
  public enum Samp {}
  public enum Script {}
  public enum Section {}
  public enum Select {}
  public enum Small {}
  public enum Source {}
  public enum Span {}
  public enum Strong {}
  public enum Style {}
  public enum Sub {}
  public enum Summary {}
  public enum Sup {}
  public enum Svg {}
  public enum Table {}
  public enum Tbody {}
  public enum Td {}
  public enum Template {}
  public enum Textarea {}
  public enum Tfoot {}
  public enum Time {}
  public enum Track {}
  public enum Th {}
  public enum Thead {}
  public enum Tr {}
  public enum U {}
  public enum Ul {}
  public enum Var {}
  public enum Video {}
}
