#if !canImport(ObjectiveC)
import XCTest

extension SnapshotTestingTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SnapshotTestingTests = [
        ("testComplexHtml", testComplexHtml),
        ("testSnapshots", testSnapshots),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(SnapshotTestingTests.__allTests__SnapshotTestingTests),
    ]
}
#endif
