name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: MacOS
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: make test-swift

  ubuntu:
    name: Ubuntu
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: make test-linux
